---
title: "Curriculum Vitae"
---

---

## **Relevant Education**

---


#### **From July 2021 - ongoing**
**PostDoc in biological oceanography at GEOMAR Helmholtz Centre for Ocean Research Kiel** under supervison of [**Prof. Anja Engel**](https://www.geomar.de/en/aengel)

---


#### **Since October 2015 - May 2021:**

**PhD student in Ecology with specialization in Marine Microbial Ecology**, under supervision of [**Prof. Jarone Pinhassi**](https://lnu.se/en/staff/jarone.pinhassi/), [**Ass. Prof. Daniel Lundin**](https://lnu.se/en/staff/daniel.lundin/) and [**Prof. Catherine Legrand**](https://lnu.se/en/staff/catherine.legrand/), [Linnaeus University](https://lnu.se/en/), Centre for Ecology and Evolution in Microbial model Systems (EEMiS), Faculty of Health and Life Sciences, Barlastgatan 11, 39182 Kalmar, Sweden.

---

#### **Between September 2018 and February 2016**

**GENECO student**, [Graduate Research School in Genomic Ecology](https://www.biology.lu.se/education/phd-studies/graduate-research-school-in-genomic-ecology), Faculty of Science, Department of Biology, Lund University, Sweden.

---

#### **Between June 2015 and March 2013:**

**MSc in Ecology with main focus on Marine Biology, Microbial Oceanography**, under supervision of [**Prof. Gerhard J. Herndl**](https://limbo.univie.ac.at/research/microbial-oceanography/) and Senior Scientist [**Dr. Thomas Reinthaler**](http://www.microbial-oceanography.eu/thomas-reinthaler/), and [**Alexander H. Frank**](https://www.whoi.edu/profile/afrank), University of Vienna, [Department of Limnology and Bio-Oceanography](https://limbo.univie.ac.at), Centre of Ecology, [University of Vienna](https://www.univie.ac.at/en/), Althanstraße 14, 1090 Vienna, Austria.

---

#### **Between February 2013 and October 2009:**

**BSc in Biology**, [University of Vienna](https://www.univie.ac.at/en/), Althanstraße 14, 1090 Vienna, Austria.

---