---
title: "Manuscripts"
---

---

> **Currently in preparation:**

* **Pontiller, B.**, Martínez-García, S., Amnebrink, D., González, JM., Lundin, D., Teira, E., Pinhassi, J. Pronounced temporal differences in bacterioplankton gene expression and succession of bacteria during phytoplankton bloom progression and decay, *Manuscript (expected submission December 2020)*

* **Pontiller, B.**, Perez-Martinez, C., Bunse, C., Osbeck CMG., Lundin, D., Pinhassi, J. Vertical depth profile associated with distinct shifts in bacterioplankton gene expression in a stratified water column, *Manuscript (expected submission spring 2021)*

* Karlsson, CMG., **Pontiller, B.**, Teikari, JE., Traving, SJ., Happel, EM., Henke, B., et al. Metatranscriptomic analysis uncovers divergent responses of Baltic Sea bacteria to forest and agriculture river loadings, *Manuscript (expected submission December 2020)*

* Bunse, C., **Pontiller, B.**, Osbeck, CMG., Fridolfsson, E., Lundin, D., Moran, MA., Mederos, P., Pinhassi, J. Seasonal bacterioplankton dynamics and DOM turnover, *Manuscript (in preparation)*

* Bunse C., Lundin D., Lindh MV., Sjöstedt J., Israelsson S., Martínez-García S., Baltar, F., Muthusamy, SD., **Pontiller, B.**, et al. Seasonality and cooccurrences of free-living Baltic Sea bacterioplankton, *Manuscript (in preparation)*

* Joglar, V., Álvarez-Salgado, XA., Gago-Martinez, A., Leao, J., Pèrez-Martínez, C., **Pontiller, B.**, Lundin, D., Pinhassi, J., Fernández, E., Teira, E., (2020) Cobalamin scarcity suggests a tight coupling between microbial producers and consumers in a coastal upwelling ecosystem. *Environmental Microbiology and Environmental Microbiology Reports (submitted 17 March 2020)*

---
