---
title: "LMO"
output: html_document
---

## **LMO**

> Linnaeus Microbial Observatory (LMO) is a time series station approximately 10 km East of Öland (Sweden) located in the Baltic Sea.

---

> More information is coming soon...

---

```{r include=F, meassage=F, warnings=F}
# if (require("ggfortify")) {
#  map.world <- map_data("world")
# }
```

```{r include=F, meassage=F, warnings=F}
require(tidyverse)
require(viridis)
```

```{r include=F, meassage=F, warnings=F}
project_stations.LMO <- read_tsv("~/Desktop/projects/my_website/website/project_stations.tsv") %>%
  filter(STATION == "LMO")

if (!require(map.world.df)) map.world.df <- map_data("world") %>% rename(gr = group)
```

```{r meassage=F, warnings=F, echo=F, fig.height=12, fig.width=12}
if (require("maps")) {
map.world.all.LMO <- ggplot(map.world.df, aes(x = long, y = lat)) +
  geom_polygon(aes(group = gr)) +
  geom_point(data=project_stations.LMO, aes(x=LONG, y=LAT, color=STATION), size=15) +
  scale_color_viridis(discrete=T, option="viridis", direction=1, begin=1 , end=1, name="Project") +
  theme(legend.text=element_text(size=22),
        legend.title=element_text(size=30)) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks = element_blank()) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_line(colour = "#3F4851")) +
  coord_map("ortho", orientation=c(56.6, 16.3, -15))
map.world.all.LMO
}
```

---
